Update electron
zingolabs/zecwallet-lite pull request #40
Opened 2022-06-05 05:35 UTC by zancas

This is @skyl 's fix to the electron dep.

2022-06-05 18:06 UTC, AloeareV requested changes

2022-06-05 18:06 UTC, AloeareV commented on native/Cargo.toml
> +zecwalletlitelib = { path = "../../../zecwalletlitelibs/dev/" }
This doesn't look like it wants to be on dev!

2022-06-05 18:06 UTC, AloeareV commented on package.json
> +    "electron": "18.2.4",
If this change just works out of the box, that's awesome!

2022-06-06 02:10 UTC, juanky201271 requested changes

2022-06-06 02:10 UTC, juanky201271 commented on native/Cargo.toml
> +zecwalletlitelib = { path = "../../../zecwalletlitelibs/dev/" }
Definitely this doesn't work in our repo.

2022-06-06 02:57 UTC, zancas commented on native/Cargo.toml
> +zecwalletlitelib = { path = "../../../zecwalletlitelibs/dev/" }
This is my mistake.   Fixing...

2022-06-06 03:05 UTC, zancas commented on native/Cargo.toml
> +zecwalletlitelib = { path = "../../../zecwalletlitelibs/dev/" }
This is my mistake.   Fixing...

2022-06-06 13:52 UTC, AloeareV approved these changes
Great!

2022-06-06 13:54 UTC, merged